name: Manual run Python script

on:
  # Этот триггер добавляет кнопку "Run workflow" на вкладке Actions.
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the script on'
        required: true
        default: 'main'

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      # Загрузка кода из репозитория.
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          
      # Настройка окружения Python.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      # Выполнение Python-скрипта.
      - name: Run Python script
        run: |
          # Укажите путь к вашему скрипту, например, 'my_script.py'
          python my_script.py
