# Имя рабочего процесса, которое будет отображаться на вкладке Actions
name: Run Python Script Manually

on:
  # Этот триггер добавляет кнопку «Run workflow» на странице Actions
  workflow_dispatch:
    inputs:
      # Поле для ввода ветки, на которой должен быть запущен скрипт
      branch:
        description: 'Branch to run the script on'
        required: true
        default: 'main'
      # Необязательное поле для ввода имени скрипта
      script_name:
        description: 'Name of the Python script to run (e.g., my_script.py)'
        required: true
        default: 'my_script.py'

jobs:
  run-python-script:
    # Определение операционной системы для раннера
    runs-on: ubuntu-latest
    
    steps:
      # Шаг 1: Загрузка кода из репозитория
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          # Использование введенной ветки для загрузки кода
          ref: ${{ github.event.inputs.branch }}
          
      # Шаг 2: Настройка окружения Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      # Шаг 3: Установка зависимостей (если они есть)
      # Если у вас есть requirements.txt, раскомментируйте следующие строки
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
          
      # Шаг 4: Запуск Python-скрипта
      - name: Run Python script
        run: |
          # Запуск скрипта, имя которого было введено вручную
          python ${{ github.event.inputs.script_name }}
